config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, except: [:index]

  resource :session, only: [:new, :create, :destroy]

  resources :bands do 
    resources :albums, only: [:new]
  end

  resources :albums, except: [:index, :new]

end

app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id         :bigint(8)        not null, primary key
#  band_id    :integer          not null
#  title      :string           not null
#  year       :integer
#  studio     :boolean          default(TRUE)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Album < ApplicationRecord

    validates :band_id, :title, presence: true

    #validate year custom 
    belongs_to :band
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/band.rb
# == Schema Information
#
# Table name: bands
#
#  id         :bigint(8)        not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Band < ApplicationRecord
    
    validates :name, presence: true

    has_many :albums
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint(8)        not null, primary key
#  user_name       :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
    include BCrypt

    attr_reader :password

    validates :password, length: { minimum: 6, allow_nil: true }
    validates :user_name, :password_digest, :session_token, presence: true
    validates :user_name, :session_token, uniqueness: true

    after_initialize :ensure_session_token!

    def self.find_by_credentials(user_name, password)
        user = User.find_by(user_name: user_name)
        if user && user.is_password?(password)
            user
        else
            nil
        end
    end

    def is_password?(password)
        Password.new(self.password_digest) == password
    end

    def password=(password)
        @password = password
        self.password_digest = Password.create(password)
    end


    def ensure_session_token!
        self.session_token ||= SecureRandom.urlsafe_base64
    end

    def reset_session_token!
        self.session_token = SecureRandom.urlsafe_base64
        self.save!
        self.session_token
    end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

    before_action :redirect_if_logged_out

    def new
        @album = Album.new
        render :new
    end

    def create
        @album = Album.new(album_params)
        if @album.save
            redirect_to album_url(@album)
        else
            flash.now[:errors] = @album.errors.full_messages
            render :new
        end
    end

    def index
        @albums = Album.all
        render :index
    end

    def show
        @album = Album.find_by(id: params[:id])
    end

    def destroy
        album = Album.find_by(id: params[:id])
        band = album.band
        album.delete
        redirect_to band_url(band)
    end

    def update
        @album = Album.find_by(id: params[:id])
        if @album.update(album_params)
            redirect_to album_url(@album)
        else
            flash.now[:errors] = @album.errors.full_messages
            render :new
        end
    end

    def edit
        @album = Album.find_by(id: params[:id])
        render :edit
    end

    private
    def album_params
        params.require(:album).permit(:title, :year, :band_id)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :current_user
    helper_method :logged_in?

    def current_user
        User.find_by(session_token: session[:session_token])
    end

    def logged_in?
        !!(current_user)
    end

    def login!(user)
        session[:session_token] = user.reset_session_token!
    end

    def redirect_if_logged_in
        redirect_to user_url(current_user) if logged_in?
    end

    def redirect_if_logged_out
        redirect_to new_session_url unless logged_in?
    end
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
    
    before_action :redirect_if_logged_out, except: [:index]

    def new
        @band = Band.new
        render :new
    end

    def create
        new_band = Band.new(band_params)

        if new_band.save
            redirect_to band_url(new_band)
        else
            flash.now[:errors] = new_band.errors.full_messages
            render :new
        end
    end

    def index
        @bands = Band.all
        render :index
    end

    def show
        @band = Band.find_by(id: params[:id])
        render :show
    end

    def destroy
        band = Band.find_by(id: params[:id])
        band.delete
        redirect_to bands_url
    end

    def update
        new_band = Band.find_by(id: params[:id])

        if new_band.update(band_params)
            redirect_to band_url(new_band)
        else
            flash.now[:errors] = new_band.errors.full_messages
            render :new
        end
    end

    def edit
        @band = Band.find_by(id: params[:id])
        render :edit
    end

    private
    def band_params
        params.require(:band).permit(:name)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    before_action :redirect_if_logged_in, only: [:new, :create]
    
    def new
        render :new
    end

    def create
        user = User.find_by_credentials(params[:user][:user_name], params[:user][:password])
        if user
            login!(user)
            redirect_to bands_url
        else
            flash.now[:erros] = "Invalid login credentials"
            render :new
        end
    end

    def destroy
        current_user.reset_session_token! if logged_in?
        redirect_to new_session_url
        #user reset session token
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    before_action :redirect_if_logged_in, only: [:new, :create]
    #sign up
    def new
        render :new
    end

    def create
        user = User.new(user_params)
        if user.save
            login!(user)
            redirect_to bands_url
        else
            flash.now[:errors] = user.errors.full_messages
            render :new
        end
    end

    def edit

    end

    def udpate

    end

    def show
        
        render :show
    end

    def destroy

    end

    private

    def user_params
        params.require(:user).permit(:user_name, :password)
    end

end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

    def auth_token
        html = "<input type=\"hidden\" "
        html += "name=\"authenticity_token\""
        html += "value=\"#{form_authenticity_token}\">"
        html.html_safe
    end

    
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/albums/_form.html.erb
<form action="<%= method == :POST ? albums_url : album_url(album) %>" method="POST">
    <input type="hidden" name="_method" value="<%= method %>">

    <%= auth_token %>

    <label>Enter Album Title:
        <input type="text" name="album[title]" value="<%= album.title %>">
    </label>

    <label>Enter Year Made:
        <input type="number" name="album[year]" value="<%= album.year %>">
    </label>

    <select name="album[band_id]">
        <% Band.all.each do |band| %>
            <option value="<%= band.id %>" <%= band.id == album.band_id ? "selected" : "" %> ><%= band.name %></option>
        <% end %>
    </select>

    <input type="submit" value="makin music!">

    <% if !flash.empty? %>
        <% flash.keys.each do |k| %>
            <%= flash[k] %>
        <% end %>
    <% end %>
</form>

app/views/albums/edit.html.erb
<h2>Lets change things UP for <%= @album.title %> by <%= @album.band.name %>!</h2>



<%= render 'form', album: @album, method: :PATCH %>

app/views/albums/new.html.erb
<h2>Time fo' some new music</h2>



<%= render 'form', album: @album, method: :POST %>

app/views/albums/show.html.erb
<h2><%= @album.title %> by <%= @album.band.name %></h2>
    <ul>
        <% @album.attributes.each do |k,v| %>
            <li><%= k %>: <%= v %></li>
        <% end %>
    </ul> 

<h3>Options</h3>
<div class="bucket">
    <form action="<%= album_url %>" method="POST">
        <input type="hidden" name="_method" value="DELETE">
        <%= auth_token %>
        <input type="submit" value="lose album"  class="button">
    </form>
    <a href="<%= edit_album_url(@album) %>" class="button">edit album</a>
    <a href="<%= band_url(@album.band) %>" class="button">Back to <%= @album.band.name %></a>
</div>

app/views/bands/_form.html.erb
<form action="<%= method == :POST ? bands_url : band_url(band) %>" method="POST">
    <input type="hidden" name="_method" value="<%= method %>">
    
    <%= auth_token %>

    <label>Enter Band Name:
        <input type="text" name="band[name]" value="<%= band.name %>">
    </label>

    <input type="submit" value="BOOM!">

    <% if !flash.empty? %>
        <% flash.keys.each do |k| %>
            <%= flash[k] %>
        <% end %>
    <% end %>
</form>

app/views/bands/edit.html.erb
<h2>Lets change things UP for <%= @band.name %>!</h2>



<%= render 'form', band: @band, method: :PATCH %>

app/views/bands/index.html.erb
<h2>All Bands</h2>

<%  @bands.each do |band| %>
    <a href="<%= band_url(band) %>" class="info"><%= band.name %></a>
<% end %>


<h3>Options</h3>
<div class="bucket">
<form action="<%= new_band_url %>" method="GET">
    <%= auth_token %>
    <input type="submit" value="New Band"  class="button">
</form>
</div>

app/views/bands/new.html.erb
<h2>Create a BAND BRO!</h2>



<%= render 'form', band: @band, method: :POST %>

app/views/bands/show.html.erb
<h2>Albums by <%= @band.name %></h2>

    <% @band.albums.each do |album| %>
        <a href="<%= album_url(album) %>">
            <p class="info"><%= album.title %></p>
        </a>
    <% end %>

<h3>Options</h3>
<div class="bucket">
    <form action="<%= new_band_album_url(@band.id) %>" method="GET">
        <%= auth_token %>

        <input type="hidden" name="band_id" value=" <%= @band.id %>">
        <input type="submit" value="New Album"  class="button">
    </form>

    <form action="<%= band_url %>" method="POST">
        <input type="hidden" name="_method" value="DELETE">
        <%= auth_token %>
        <input type="submit" value="Disband"  class="button">
    </form>

    <form action="<%= edit_band_url(@band) %>" method="GET">
        <%= auth_token %>
        <input type="submit" value="Edit"  class="button">
    </form>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <header>
  <nav>
    <a href="<%= bands_url %>" class="button" id="all_bands">All Bands</a>
    <% if logged_in? %>
      <form action="<%= session_url %>" method="POST">
        <%= auth_token %>
        <input type="hidden" name="_method" value="DELETE">
        <input class="button" type="submit" value="Log Out <%= "#{current_user.user_name}" %>">
      </form>
    <% else %>
      <a href="<%= new_session_url %>" class="button">Sign In</a>
      <a href="<%= new_user_url %>" class="button">Sign Up</a>
    <% end %>
  </nav>

  <h1>Music App</h1>

  </header>
  
  <body>

    <br>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<br>

<form action="<%= users_url %>" method="POST">

    <%= auth_token %>

    <label for="user_name">User Name:</label>
    <input id="user_name" type="text" name="user[user_name]">
    <br>

    <label for="password">Password:</label>
    <input id="password" type="password" name="user[password]">

    <input type="submit" value="Create!">
    
    <br>
    <% if !flash.empty? %>
        <% flash.keys.each do |k| %>
            <%= flash[k] %>
        <% end %>
    <% end %>

</form>

app/views/users/show.html.erb
<h1>You completed sign up or login!</h1>
<% if false %>
<ul>
    <% @user.attributes.each do |name, value| %>
        <li><%= "#{name}: #{value}" %></li>
    <% end %>
</ul>

<% end %>